# This file is part of Markerless-3D-Human-Cobot-Pose-Estimation
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Portions derived from Ultralytics YOLO, Copyright © Ultralytics Inc., AGPL-3.0.

import cv2
import numpy as np
from ultralytics import YOLO
import os
import pandas as pd
import re

# === PARAMETERS AND PATHS ===

# Camera intrinsic parameters (for reprojection from 2D + depth to 3D)
# use get_intrinsics() for getting the RealSense parameters (es. https://dev.realsenseai.com/docs/projection-in-intel-realsense-sdk-20)
fx, fy = 616.733154296875, 616.3325805664062
cx, cy = 418.6494445800781, 229.25515747070312
DEPTH_SCALE = 1000.0  # Depth is in millimeters, will convert to meters

# Input folders (the same putted in the previous RGB-D extraction script)
rgb_image_dir = r"path/to/your/rgb_and_depth_frames"
output_dir = rgb_image_dir  # Save output video/CSV in the same folder, or change as needed

# Path to the timestamp CSV generated by the previous RGB-D extraction script
timestamps_csv = os.path.join(rgb_image_dir, 'frame_timestamps.csv')
timestamps_df = pd.read_csv(timestamps_csv)
timestamps_dict = dict(zip(timestamps_df['frame_index'], timestamps_df['time_of_arrival_ms']))

# === YOLO MODELS ===
model_cobot = YOLO(r"path/to/yolo/cobot_model.pt")      # Custom YOLO model for cobot
model_human = YOLO(r"path/to/yolo/yolov8n-pose.pt")    # Human pose estimation pre-trained model (automatically loaded once you import Ultralytics)

# === VISUALIZATION PARAMETERS ===
BOX_CONF_THR = 0.5
KPT_CONF_THR = 0.3

# Skeleton connections
CONN_HUMAN = [(5,7),(7,9),(6,8),(8,10),(5,6),(5,11),(6,12)] 
CONN_COBOT = [(0,1),(1,2),(2,3),(3,4),(4,5),(5,6),(6,7),(7,8),(8,9),(9,10),(9,11)] 
ALLOWED_HUMAN_KPTS = sorted({i for pair in CONN_HUMAN for i in pair})
# of note, in the visualization, only the human keypoints of the torso and arms are drawn on the video
# To show all connections, refer to https://github.com/Alimustoofaa/YoloV8-Pose-Keypoint-Classification
# In the output CSV file, all keypoints are saved, provided they meet the CONF_THR 
# Look here for the complete information you can get from YOLO models: https://docs.ultralytics.com/tasks/pose/


# Colors and aesthetics for visualization
COLOR_BOX_HUMAN = (60, 220, 20)
COLOR_BOX_COBOT = (255, 170, 30)
COLOR_TEXT      = (0, 0, 0)
COLOR_KPT_HUMAN = (0, 255, 255)
COLOR_KPT_COBOT = (255, 0, 255)
LINE_THICKNESS  = 2
KPT_RADIUS      = 4

# === DRAWING FUNCTIONS FOR THE ANNOTATED VIDEO ===
def draw_labelled_box(img, box, class_name, obj_id, conf, color_box, color_text=(0,0,0)):
    """Draw bounding box with label."""
    x1, y1, x2, y2 = map(int, box)
    cv2.rectangle(img, (x1, y1), (x2, y2), color_box, LINE_THICKNESS)
    id_str = f" ID:{int(obj_id)}" if obj_id is not None else ""
    label = f"{class_name}{id_str} {conf:.2f}"
    (tw, th), bl = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
    y1_txt = max(0, y1 - th - 6)
    cv2.rectangle(img, (x1, y1_txt), (x1 + tw + 6, y1_txt + th + 6), color_box, -1)
    cv2.putText(img, label, (x1 + 3, y1_txt + th + 2),
                cv2.FONT_HERSHEY_SIMPLEX, 0.6, color_text, 2, cv2.LINE_AA)

def draw_skeleton(frame, kpts_xy, kpts_conf, connections, line_color, kpt_color,
                  kpt_conf_thr=0.25, thickness=2, kpt_radius=4, allowed_kpt_indices=None):
    """Draw skeleton lines and keypoints."""
    K = kpts_xy.shape[0]
    # Draw lines
    for (i, j) in connections:
        if i < K and j < K:
            ci = kpts_conf[i] if kpts_conf is not None else 1.0
            cj = kpts_conf[j] if kpts_conf is not None else 1.0
            if (ci is None or ci >= kpt_conf_thr) and (cj is None or cj >= kpt_conf_thr):
                xi, yi = int(kpts_xy[i, 0]), int(kpts_xy[i, 1])
                xj, yj = int(kpts_xy[j, 0]), int(kpts_xy[j, 1])
                cv2.line(frame, (xi, yi), (xj, yj), line_color, thickness, cv2.LINE_AA)
    # Draw keypoints
    indices = range(K) if (allowed_kpt_indices is None) else allowed_kpt_indices
    for idx in indices:
        if idx >= K:
            continue
        c = kpts_conf[idx] if kpts_conf is not None else 1.0
        if c is None or c >= kpt_conf_thr:
            x, y = int(kpts_xy[idx, 0]), int(kpts_xy[idx, 1])
            cv2.circle(frame, (x, y), kpt_radius, kpt_color, -1, cv2.LINE_AA)

# === PREPARE VIDEO OUTPUT ===

# Estimate FPS from timestamps (if available)
if 'time_of_arrival_ms' in timestamps_df.columns and len(timestamps_df) >= 2:
    deltas_ms = np.diff(timestamps_df['time_of_arrival_ms'].values)
    valid = deltas_ms[deltas_ms > 0]
    fps = 1000.0 / np.median(valid) if valid.size > 0 else 25.0
else:
    fps = 15.0 # Or change in case it is needed

# Get frame size from first available RGB image
rgb_files = sorted([f for f in os.listdir(rgb_image_dir) if f.startswith("rgb_frame_") and f.endswith(".png")])
if not rgb_files:
    raise RuntimeError("No RGB frames found in rgb_image_dir")
sample = cv2.imread(os.path.join(rgb_image_dir, rgb_files[0]))
H, W = sample.shape[:2]

fourcc = cv2.VideoWriter_fourcc(*'mp4v')
video_output_path = os.path.join(output_dir, "annotated_video_human_cobot.mp4")
writer = cv2.VideoWriter(video_output_path, fourcc, fps, (W, H))

frame_count = 0
data_rows   = []

def frame_index_from_name(name: str) -> int:
    """Extract frame index from filename, e.g. rgb_frame_000123.png -> 123"""
    m = re.findall(r'(\d+)', name)
    return int(m[-1]) if m else -1

# === MAIN PROCESSING LOOP ===

# Process images one by one
for frame_file in rgb_files:
    rgb_path   = os.path.join(rgb_image_dir, frame_file)
    depth_path = rgb_path.replace("rgb_frame_", "depth_frame_").replace(".png", ".npy")

    rgb_frame = cv2.imread(rgb_path)
    depth_map = np.load(depth_path)

    if rgb_frame is None or depth_map is None:
        print(f"Error loading {rgb_path} or {depth_path}")
        continue
        
    # Apply both YOLO models
    results_cobot = model_cobot(rgb_frame)
    results_human = model_human(rgb_frame)

    cur_frame_idx   = frame_count
    time_of_arrival = timestamps_dict.get(frame_index_from_name(frame_file), -1)

    # --- Extract and save 3D keypoints for both models (long format, per-keypoint row) ---
    for mname, results in [("Cobot", results_cobot), ("Human", results_human)]:
        if not (results and results[0].keypoints is not None):
            print(f"Frame {cur_frame_idx} - {mname}: No keypoints detected.")
            continue

        kp_raw         = results[0].keypoints.data.cpu().numpy()[0]
        keypoints_xy   = kp_raw[:, :2]
        keypoints_conf = kp_raw[:, 2]

        # Extract depth (Z) for each keypoint
        z_values = []
        for x2d, y2d in keypoints_xy:
            xi, yi = int(x2d), int(y2d)
            if 0 <= yi < depth_map.shape[0] and 0 <= xi < depth_map.shape[1]:
                z_values.append(depth_map[yi, xi] / DEPTH_SCALE)
            else:
                z_values.append(0)
        # 3D coordinates and reprojection
        keypoints_real = []
        keypoints_reproj = []
        for (x2d, y2d), z in zip(keypoints_xy, z_values):
            if z > 0:
                X = (x2d - cx) * z / fx
                Y = (y2d - cy) * z / fy
                u = (X * fx) / z + cx # x_reproj
                v = (Y * fy) / z + cy # y_reproj
            else:
                X = Y = 0.0
                u = v = np.nan
            keypoints_real.append((X, Y, z))
            keypoints_reproj.append((u, v))
            # Reprojected keypoints (x_reproj, y_reproj) are computed by projecting the reconstructed 3D point
            # back onto the image plane using camera intrinsics. This allows to check the consistency of the 3D reconstruction.
            # If the process is correct, reprojected points should be close to the original 2D detections.
            # Useful for debugging, calibration validation, and for identifying outliers.

        # SAVE CSV 
        for i, ((X, Y, z), conf, (x2d, y2d), (x_reproj, y_reproj)) in enumerate(
            zip(keypoints_real, keypoints_conf, keypoints_xy, keypoints_reproj)
        ):
            if conf >= KPT_CONF_THR:
                row = {
                    'frame': cur_frame_idx,
                    'time_of_arrival_ms': time_of_arrival,
                    'model': mname, # cobot or human
                    'keypoint_index': i, 
                    'x2d': float(x2d),
                    'y2d': float(y2d),
                    'x': float(X),
                    'y': float(Y),
                    'z': float(z),
                    'x_reproj': float(x_reproj),
                    'y_reproj': float(y_reproj),
                    'confidence': float(conf)
                }
                data_rows.append(row)
# **********************************************************************
# Important note on keypoint indexing:
# In the paper, the cobot keypoints are numbered in the range 1–12.
# However, in the actual configuration file, the range is 0–11.
# This means that the keypoint used in the pose estimation validation 
# corresponds to index 8, not 9, in the configuration reconstruction.
# **********************************************************************


    # --- Annotate image: boxes, labels, skeletons for both models ---

    # Cobot
    if results_cobot and results_cobot[0] is not None:
        r = results_cobot[0]
        # Boxes
        if r.boxes is not None and len(r.boxes) > 0:
            xyxy = r.boxes.xyxy.cpu().numpy()
            confs = r.boxes.conf.cpu().numpy()
            cls_ids = r.boxes.cls.cpu().numpy().astype(int) if r.boxes.cls is not None else np.zeros(len(xyxy), dtype=int)
            ids = r.boxes.id.cpu().numpy() if (hasattr(r.boxes, "id") and r.boxes.id is not None) else [None] * len(xyxy)
            names = getattr(r, "names", None)
            for i, box in enumerate(xyxy):
                class_name = (names[cls_ids[i]] if names is not None and cls_ids[i] in names else "cobot")
                draw_labelled_box(rgb_frame, box, class_name, ids[i], confs[i], COLOR_BOX_COBOT, COLOR_TEXT)
        # Skeleton
        if r.keypoints is not None:
            kxy = r.keypoints.xy.cpu().numpy()
            try:
                kcf = r.keypoints.conf.cpu().numpy()
            except Exception:
                kcf = None
            for i in range(kxy.shape[0]):
                draw_skeleton(
                    rgb_frame, kxy[i], kcf[i] if kcf is not None else None,
                    connections=CONN_COBOT,
                    line_color=COLOR_BOX_COBOT, kpt_color=COLOR_KPT_COBOT,
                    kpt_conf_thr=KPT_CONF_THR,
                    thickness=LINE_THICKNESS, kpt_radius=KPT_RADIUS,
                    allowed_kpt_indices=None
                )

    # Human
    if results_human and results_human[0] is not None:
        r = results_human[0]
        if r.boxes is not None and len(r.boxes) > 0:
            xyxy = r.boxes.xyxy.cpu().numpy()
            confs = r.boxes.conf.cpu().numpy()
            cls_ids = r.boxes.cls.cpu().numpy().astype(int) if r.boxes.cls is not None else np.zeros(len(xyxy), dtype=int)
            ids = r.boxes.id.cpu().numpy() if (hasattr(r.boxes, "id") and r.boxes.id is not None) else [None] * len(xyxy)
            names = getattr(r, "names", None)
            for i, box in enumerate(xyxy):
                class_name = (names[cls_ids[i]] if names is not None and cls_ids[i] in names else "human")
                draw_labelled_box(rgb_frame, box, class_name, ids[i], confs[i], COLOR_BOX_HUMAN, COLOR_TEXT)
        if r.keypoints is not None:
            kxy = r.keypoints.xy.cpu().numpy()
            try:
                kcf = r.keypoints.conf.cpu().numpy()
            except Exception:
                kcf = None
            for i in range(kxy.shape[0]):
                draw_skeleton(
                    rgb_frame, kxy[i], kcf[i] if kcf is not None else None,
                    connections=CONN_HUMAN,
                    line_color=COLOR_BOX_HUMAN, kpt_color=COLOR_KPT_HUMAN,
                    kpt_conf_thr=KPT_CONF_THR,
                    thickness=LINE_THICKNESS, kpt_radius=KPT_RADIUS,
                    allowed_kpt_indices=ALLOWED_HUMAN_KPTS
                )

    # Write annotated frame to video
    writer.write(rgb_frame)
    frame_count += 1

# === SAVE CSV WITH ALL KEYPOINTS 3D INFO (LONG FORMAT) ===
csv_output_path = os.path.join(output_dir, "keypoints_3d_long_with_confidence.csv")
df_out = pd.DataFrame(data_rows)
df_out.to_csv(csv_output_path, index=False)
print(f"[✓] CSV saved with 2D/3D/reprojected coordinates and confidence: {csv_output_path}")

# === FINALIZE VIDEO WRITER ===
writer.release()
print(f"[✓] Annotated video saved: {video_output_path}  (FPS≈{fps:.2f}, size={W}x{H})")

# === USEFUL REFERENCES ===
# https://github.com/orgs/ultralytics/discussions/18822#discussioncomment-12688529

# https://dev.realsenseai.com/docs/projection-in-intel-realsense-sdk-20
