# Data
path: C:\Users\egle_\OneDrive\Desktop\yolo\yolo_pose\data
train: images\train  # train images (relative to 'path')
val: images\val  # val images (relative to 'path')

# Keypoints
kpt_shape: [12, 3]  # [number of keypoints, number of dim]
flip_idx: []
# Others
patience: 100  # Interrompi se la validazione non migliora per 10 epoch
augment: true
mosaic: 0.5
mixup: 0.5
hsv_h: 0.02
hsv_s: 0.4
hsv_v: 0.3
fliplr: 0.0
scale: 0.3
translate: 0.2
degrees: 10.0
shear: 1.0
# Classes
names: ['Cobot']             # Class names

